### ISSUE TITLE
Enhance installer with auto compile

### ISSUE THREAD

**Issue by stevenklar** [ayecue/greybel-js#106]
Right now I can only see that files get created with the correct content.
I was wondering why there is no feature to also "compile them right away".
This can prevent leaving the lib src code on the machine.

Is this a limitation due to multiple installer files when having too much code? Or did I just not see the option? ;-)

It might just take an additional parameter which enhances the installer with

- compile the created files `build(src, dest)`
- delete the created files

Shouldn't be much of an effort.
After that one could compile the installer, run it and remove the installer - everything was already compiled and is ready to be used.

**Comment by ayecue** [comment]
Hey @stevenklar,

just to make sure you are speaking about this feature https://github.com/ayecue/greybel-js#auto-create-files-in-game right?

> Is this a limitation due to multiple installer files when having too much code? Or did I just not see the option? ;-)

No there is no limitation and no there is no option right now to do that. I just thought not compiling straight away keeps more options for the user. ;)

> It might just take an additional parameter which enhances the installer with

Sure I can add an option to compile it straight away.

Thanks for the suggestion.

**Comment by ayecue** [comment]
> Did not mean the auto create files feature. But you already understood what I mean. (-i / --installer flag.)

Actually I did not understand what you meant then. 😄 But I got it now you mean that at the end of the installers it should build the files and delete them again. I mean yeah I can add that shouldn't be too much work.

**Comment by stevenklar** [comment]
Exactly! This let us compile & run the installer and we don't need to delete the src files by hand.
My point is that this prevents accidentally leak the whole source code.

This is what I suggest as a new installer flow:
- Create all src files
- Compile these files
- Delete all source files
- Delete installer.src
=> Tool can be obtained by another player but source code is not leaked (to non mods/admins) at least.

**Comment by ayecue** [comment]
Feature should be available now with https://github.com/ayecue/greybel-js/pull/107 - 2.0.9.

**Comment by ayecue** [comment]
I'll close the ticket for now, in case there are issues this ticket may be reopned or a new one created.
