### ISSUE TITLE
save/build request

### ISSUE THREAD

**Issue by gatekeeper258** [ayecue/greybel-js#155]
Can I request the option when pressing F7 to build that it saves before doing the build?

**Comment by ayecue** [comment]
Sure should be a quick one to implement. I'll give an update once it's implemented.

**Comment by gatekeeper258** [comment]
yes im sorry, for the vs code version

**Comment by ayecue** [comment]
Alright I've merged https://github.com/ayecue/greybel-vs/pull/170 which includes the change. Should be deployed in the next 5 minutes making version 2.1.17 available.

**Comment by gatekeeper258** [comment]
thabk you sir!!!

.
