### ISSUE TITLE
Uglify build mode does not handle "globals"

### ISSUE THREAD

**Issue by smiley8D** [ayecue/greybel-js#157]
Uglify appears to handle 'globals' as a user-defined variable. When I build the following code with uglifiy:

`print globals`

the resulting uglified code  is this:

`print(H)`

Greyhack then errors because `H` was never defined. I believe it should instead generate this:

`print(globals)`

**Comment by ayecue** [comment]
Hey,

thanks for reporting.

Seems like this issue is already open since 14.01 which is kinda odd since I didn't see it. Anyway I'll look into it.

**Comment by ayecue** [comment]
Just released a new version for greybel-js, greybel-vs and miniscript-vs. Should fix the issue for all of those. In case you're still expiring the same problems feel free to reopen this issue.

**Comment by smiley8D** [comment]
Thanks ayecue, I'll take a look. As for the issue date, my GitHub had been silently flagged and I didn't realize the issue was hidden.
