### ISSUE TITLE
Message-Hook sync sometimes open unusable Terminal window

### ISSUE THREAD

**Issue by stevenklar** [ayecue/greybel-js#159]
When using the sync it always works, but sometimes spawn an Terminal window which is unusable:

```bash
mtx@nop:~$ s
unknown error: can't find remote process
mtx@nop:~$ ls
unknown error: can't find remote process
```

**Comment by ayecue** [comment]
New dll should be in place now (version 0.3). The issue should now be resolved and the window should close instantly after the actions are executed.

Thanks for the support @stevenklar. Closing ticket for now.
