### ISSUE TITLE
Message-Hook does not sync installer and auto compile

### ISSUE THREAD

**Issue by stevenklar** [ayecue/greybel-js#160]
This is a feature request.

It would be nice to not only sync the compiled src but also compile it and remove the src to prevent accidentally leak the src.
This would result in a realtime sync of the tool without manual build and rm of the src.

By e. g. either use the ShellIntrinsic "build" or PlayerServerMethods "BuildScriptServerRpc" when --instlal & --auto-compile flag is giving to the greybel compiler which then should use the installer*.src

Bonus perfect would be to rm the src after successful build.

**Comment by ayecue** [comment]
Auto-compile for in-game creation should be now in place. Please take a look if it fits your needs.
