### ISSUE TITLE
Change where this tool outputs build results (i.e. resulting files) to [Feature Request]

### ISSUE THREAD

**Issue by Arc8ne** [ayecue/greybel-js#178]
While using this tool, I have noticed that when building the files, the result (i.e. resulting files) of the build are outputted into a folder called "build" which is then stored in the output folder located at the path specified by the ``output`` argument.

As a result, I was wondering if the behavior of this tool could be updated such that the result (i.e. resulting files) of the build would be directly outputted into the output folder located at the path specified by the ``output`` argument?

If necessary, I can provide further elaborations and details regarding this feature request.

**Comment by ayecue** [comment]
Hey, thanks for the feature request. Yes I can indeed add this option shouldn't be a problem. 

Just wondering is this a duplicate of https://github.com/ayecue/greybel-js/issues/177 since the description sounds pretty similar or is there any difference?

**Comment by Arc8ne** [comment]
> Hey, thanks for the feature request. Yes I can indeed add this option shouldn't be a problem.
> 
> Just wondering is this a duplicate of #177 since the description sounds pretty similar or is there any difference?

Hi there, thank you.

This issue is not a duplicate of #177, in face, #177 is a separate issue which is why I had created a separate issue for it.

#177 is concerned with the fact that the tool currently outputs a folder called "build" in the specified output folder, instead of just placing the built files (i.e. the files resulting from the build such as the installer file and the minified source code file) directly into the specified output folder. Hence, this issue is not a duplicate of #177 and is instead a separate issue from #177.

**Comment by Arc8ne** [comment]
> Hey, thanks for the feature request. Yes I can indeed add this option shouldn't be a problem.
> 
> Just wondering is this a duplicate of #177 since the description sounds pretty similar or is there any difference?

Hi there, thank you and thanks for the response.

With regards to your question, in theory, this issue and #177 are not duplicates of one another. However, if this issue is resolved, then #177 would pretty much no longer be an issue.

**Comment by ayecue** [comment]
In order to keep backwards compatibility I've decided instead to introduce a option called `--no-build-folder` instead. By using that option it will put the output directly into the destination folder without wrapping it into a build folder. It will be part of `3.2.16`.

**Comment by Arc8ne** [comment]
> In order to keep backwards compatibility I've decided instead to introduce a option called `--disable-build-folder`. By using that option it will put the output directly into the destination folder without wrapping it into a build folder. It will be part of `3.2.16`.

I see, thanks.

**Comment by ayecue** [comment]
Should be available now with `3.2.16` released.

**Comment by Arc8ne** [comment]
I see, thank you.

**Comment by Arc8ne** [comment]
Since this issue has been resolved in ``3.2.16``, I will close it.

Thanks again for helping to resolve the issue.
