### ISSUE TITLE
Add CLI option to specify the name of the outputted executable file

### ISSUE THREAD

**Issue by Arc8ne** [ayecue/greybel-js#182]
Currently, the name of the outputted executable file is dependent on the name of the entrypoint source code file.

Is it alright if an additional CLI option (that could be called something like ``--executable-name`` or ``--program-name``) could be added that would allow the user to specify the name of the executable file that would be outputted either after auto-compilation or after running the generated installer script in Grey Hack?

**Comment by Arc8ne** [comment]
> Hey, sure that would be possible. Just one question regarding the request. It should only define the in-game executable name right?
> 
> 
> 
> EDIT: Actually nvm your description already answers my question. 😅 I'll look into it.

I see haha, thank you.

**Comment by ayecue** [comment]
I've created a PR https://github.com/ayecue/greybel-js/pull/183 which contains the option `--auto-compile-name` which should cover your requested functionality. I am probably going to merge the PR tomorrow since I didn't had enough time yet to test around.

**Comment by Arc8ne** [comment]
> I've created a PR https://github.com/ayecue/greybel-js/pull/183 which contains the option `--auto-compile-name` which should cover your requested functionality. I am probably going to merge the PR tomorrow since I didn't had enough time yet to test around.

I see, thank you.

**Comment by ayecue** [comment]
No worries 🙂 

I've just merged `3.2.17` so `--auto-compile-name` should be available now. I'll close the ticket for now. If you see any issues feel free to reopen the ticket.
