### ISSUE TITLE
Envar not working

### ISSUE THREAD

**Issue by stevenklar** [ayecue/greybel-js#24]
Hey

tried to get envar working with:
`greybel --env-vars=random=bla src/cmd.src .`
and also by using env files:
`greybel src/cmd.src . -ev local.conf`

**local.conf**
```
# MY COMMENT
random=SOME_VALUE
```
***cmd.src***
```
...
somevar = #envar random;
...
```

**Build result**
```
globals.H=globals
MODULES={}
EXPORTED={}
__REQUIRE=function(r)
if not MODULES.hasIndex(r) then
exit((("Module " + r) + " cannot be found..."))
end if
module=MODULES[r]
return @module(r).exports
end function
MAIN=function()
ENV={}
somevar=null
print("\x90     ")
print("\x90     n0p")
print("\x90     ")
print(somevar)
end function
MAIN()
```

Any idea why that is only return "null" on build?

**Comment by stevenklar** [comment]
After some investigation and debugging there is a finding.

The transpiler does not forward the options to the parser.
https://github.com/ayecue/greybel-transpiler/blob/master/src/transpiler.ts#L86
Fixed it by replacing 
```
		const targetParseResult: TargetParseResult = await target.parse({
			disableLiteralsOptimization: me.disableLiteralsOptimization,
			disableNamespacesOptimization: me.disableNamespacesOptimization
		});
```
with
```
		const targetParseResult: TargetParseResult = await target.parse(me);
```

**Comment by ayecue** [comment]
You are right. Looks like I've missed that.

Your patch looks alright at first glance. I'll have deeper look tomorrow.

**Comment by ayecue** [comment]
Okay the issue should be fixed with https://github.com/ayecue/greybel-js/commit/e47e653c250b0e319bd00b4a60779a92c64d83fa.

Turns out that the envars map wasn't just passed to the target class incorrectly but also to the parser instance from `greybel-core`. To prevent future mistakes I've also added a test case for it.

Thanks for reporting. :)

I'll keep the issue open for now until you have also checked it on your side.

**Comment by stevenklar** [comment]
Hey ayecue, checked out the new version and it works!

There is one more thing I noticed.
I don't know if we could fix that within this issue or should create a new one for it.

Right now I got the ENV implementation in my actual entry src file. Which works now.
Example:

**cmd.src (which is build target)**
```
Framework.ENV.Mode = #envar MODE; // local or remote
```

When I put that in any file which will be merged ob build time. Meaning #include env;
Having the same line in there produces
```
Framework.ENV.Mode = null;
```

Any idea if that could be an easy fix or does that need more brain being able to make that recursive.
I don't think it's really a deal breaker with that feature. But having all env related stuff injected in another file would be nice. :-)

**Comment by ayecue** [comment]
Nice good to hear.

Thanks for reporting. I thought I've added support for it at some point. Seems like I didn't. The passing of the environment variables map right now is a little bit dirty in the transpiler. Something I have to clean up in the future when there is time.

Anyway I've did a few changes to the code in the transpiler. Greybel should now support `#envar somevar;` in includes and imports. I've also added a test case to make sure this works in the future as well.

Please give it a try if it works for you as well.

I'll keep the issue open until you've checked it on your side as well.

**Comment by stevenklar** [comment]
Works like a charm! Thank you for working on this. I love to develop outside of greyhack as it's much more convinient and greybel is an insane improvement on that.

Closing this issue now. Fixed and better than before. 👍🏼
