### ISSUE TITLE
Misbehavior in the built-in range function

### ISSUE THREAD

**Issue by Zeta314** [ayecue/greybel-js#26]
There is a misbehavior in the builtin range function, where:
- In greybel-js, it considers the **end** parameter as **excluded**
- In the actual game, it considers the **end** parameter as **included**

Snippet to check:
`print(range(0, 4))`

In greybel-repl (or greybel-execute) it will output `[0, 1, 2, 3]`, whereas in the game it will output `[0, 1, 2, 3, 4]`.

**Comment by ayecue** [comment]
Thanks for the report I gonna take a look.

**Comment by ayecue** [comment]
Should be fixed with version `1.2.2`. (https://github.com/ayecue/greybel-js/commit/df45d8615b77328a1bebe1cc6aae385d51fd0e55)

Going to close the ticket.
