### ISSUE TITLE
List can be different even if the same

### ISSUE THREAD

**Issue by brahermoon** [ayecue/greybel-js#32]
Dear Developer(s),
I recently build something in gs and came across this bug :
if I have an object with an List in an attribute and check if it is the same as an List that should have the same value.
Ingame it tells me they are the same but the interpreter thats also used in your vscode extension tells something different. 
My code can be found in the attachments section
[ArrayBufferBug.txt](https://github.com/ayecue/greybel-js/files/9608736/ArrayBufferBug.txt)

**Comment by ayecue** [comment]
Hey thanks for reporting.

You are right it seems like maps/list in GS actually do a deep equal. This behavior needs to be added into the greybel interpreter.

I'll update the ticket as soon I've released a fix for this which will be probably in a few days.

**Comment by ayecue** [comment]
Should be fixed with: https://github.com/ayecue/greybel-js/commit/6321b550db478e896803421e7777e8fcd66155f3
